#!/bin/sh

mkdir -p "$SNAP_USER_COMMON"
cd "$SNAP_USER_COMMON"
if [ "$1" = "--version" ] || [ "$1" = "-V" ]; then
    echo "Oranguru Local $SNAP_VERSION"
elif [ "$1" = "help" ] || [ "$1" = "--help" ] || [ "$1" = "-h" ]; then
    "$SNAP/bin/oranguru" help --snap
else
    ORANGURU_PORTS_FILE="$SNAP_COMMON/ports" "$SNAP/bin/oranguru" "$@"
fi
